# Azure Pipeline for Java using Maven
# Builds, runs tests, publishes artifacts

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Checkout source code
- checkout: self

# Use JDK 17
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Run Maven build
- task: Maven@4
  inputs:
    mavenPomFile: 'Javateam/pom.xml'   # Adjust if pom.xml is elsewhere
    goals: 'clean install'
    options: '-DskipTests'
    javaHomeOption: 'Path'
    jdkDirectory: $(JAVA_HOME)         # Uses Java 17 from JavaToolInstaller
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Unit Tests'
  condition: succeededOrFailed()

# Publish build artifact (JAR/WAR)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Javateam/target'   # Ensure this path matches output
    ArtifactName: 'drop'
    publishLocation: 'Container'
